import type { Metadata } from "next";
import { Inter, Lato, Urbanist,Titillium_Web,Amaranth } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { cn } from "@/lib/utils";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { SideBar } from "./components/SideBar";
import { Toaster } from "sonner";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { Navbar } from "./components/Navbar";
import BottomBar from "./components/BottomBar";
import NextTopLoader from 'nextjs-toploader';


const lato = Lato({ weight:"400", subsets: ["latin"] });
const urbanist = Urbanist({ weight:"400", subsets: ["latin"] });
const titillium_Web = Titillium_Web({ weight:"400", subsets: ["latin"] });
export const amaranth = Amaranth({ weight:"400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(titillium_Web.className , "bg-none")}>
        <main >
          <NextSSRPlugin
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          <NextTopLoader />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Navbar /> */}
            {children}
          </ThemeProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
